<a href="https://colab.research.google.com/github/Adrianopogianeli/deep_learning_with_pyhon_sencond_edition/blob/master/chapter_2_my_first_deep_learning_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Listing 2.1 Loading the MNIST dataset in keras
!pip install tensorflow
from tensorflow.keras.datasets import mnist


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#class = classification problem
#samples = Data points
#label = the class associated with a specific sample
(train_images, train_labels),(test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_images)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
#Listing 2.2 The network architecture
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10,activation="softmax")
]
)

In [10]:
#Listing 2.3 The compilation step
model.compile(optimizer = "rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [11]:
#Listing 2.4 Preparing the image data
train_images = train_images.reshape((60000,28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [13]:
#Listing 2.5 "Fitting" the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 2s 3ms/step - loss: 0.2561 - accuracy: 0.1001
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1031 - accuracy: 0.0993
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0685 - accuracy: 0.0988
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0494 - accuracy: 0.0989
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0369 - accuracy: 0.0989


In [14]:
#Listing 2.6 Using the model to make predictions
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

array([2.09843222e-07, 3.87769816e-10, 5.16692990e-06, 1.55110247e-04,
       4.07811995e-13, 7.03011779e-07, 4.93951160e-15, 9.99827623e-01,
       2.75450162e-07, 1.09080565e-05], dtype=float32)

In [15]:
#Each number on index i in the above array correspond to the probability that digit image test_images[0] belongs to claas i
#Highest probability score 9.99827623e-01 at the index 7, so according to out model, it must be a 7
predictions[0].argmax()

7

In [16]:
predictions[0][7]

0.9998276

In [17]:
#We can check that the test label agrees:
test_labels[0]

7

In [18]:
#Listing 2.7 Evaluation the model on new data
test_lost, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 2ms/step - loss: 0.0697 - accuracy: 0.0999
test_acc: 0.09989999979734421
